---
- name: Push data images
  hosts: all
  vars:
    s3_host: "{{s3_host}}"
    s3_bucket_name: "{{s3_bucket_name}}"
    picture_obj_key: "{{picture_obj_key}}"
    s3_access_key: "{{s3_access_key}}"
    s3_secret_key: "{{s3_secret_key}}"
    job_id: "{{job_id}}"
    result_dir: /var/lib/docker/volumes/naomesh-orion-orchestrator_s3data/_data/mvs
  tasks:
    - name: get images in remote
      find:
        paths: "{{ result_dir }}"
        file_type: file
        patterns:
          - "*.jpg"
          - "*.png"
          - "*.JPG"
          - "*.PNG"
          - "*.ply"
      register: file_list
    - name: put s3_bucket_items
      aws_s3:
        s3_url: "{{s3_host}}"
        bucket: "{{s3_bucket_name}}"
        object: "/{{job_id}}/results/{{item.path | basename}}"
        encrypt: no
        src: "{{ item.path }}"
        mode: put
        aws_access_key: "{{s3_access_key}}"
        aws_secret_key: "{{s3_secret_key}}"
      with_items: "{{file_list.files}}"
